# Generated by Django 2.1.3 on 2018-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
